### ISSUE TITLE
[Feature] Add list for generated stories

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/storybook-gpt#11]
**Is your feature request related to a problem? Please describe.**
This web app doesn't have a list of generated stories.

**Describe the solution you'd like**
Would be nice to have a list under the generator to contain all the generated stories.
The user should be able to delete any of the generated stories from the list.
Local storage can be used to save and retrieve the generated stories.
When the user clicks on any of the saved stories it should appear in the generator.

**Comment by danyelica** [comment]
Can you assign to me please? I would like to do this issue
