### ISSUE TITLE
[Feature] Allow User To Toggle between light/dark mode

### ISSUE THREAD

**Issue by etnlbck** [eduardconstantin/storybook-gpt#12]
As a user, I would like to interact with the UI depending on my light or dark preference.

**Comment by rjwignar** [comment]
I would like to try this out. Would a simple light/dark toggle button suffice?

**Comment by KriteshTimsina** [comment]
Assign me!

**Comment by eduardconstantin** [comment]
> I would like to try this out. Would a simple light/dark toggle button suffice?

Yes, but it also has to be functional
