### ISSUE TITLE
[Feature] CLI - Scan my project, generate stories, write to filesystem

### ISSUE THREAD

**Issue by etnlbck** [eduardconstantin/storybook-gpt#14]
This might be more of an Epic than a feature. 
The idea of copying and pasting via the browser is nice. But maybe there's an opportunity to add a standalone CLI with vite, webpack, CI/CD integrations.

**Comment by eduardconstantin** [comment]
I already have a CLI with this feature
[https://github.com/eduardconstantin/storybook-genie](https://github.com/eduardconstantin/storybook-genie)

**Comment by etnlbck** [comment]
@eduardconstantin Sweet! I'll take a look. Thanks.
