### ISSUE TITLE
[BUG] Light mode input style

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/storybook-gpt#17]
**Describe the bug**
When switching to light mode the input and label for the component name is not styled correctly

**Expected behavior**
The style should be similar to the rest of the inputs

![image](https://github.com/eduardconstantin/storybook-gpt/assets/9199763/aecab076-cacf-44dc-9540-f2846f122e7a)

**Comment by Pinaka-Pani-18** [comment]
I would like to work on this issue, Could you please assign me this issue ?
