### ISSUE TITLE
Migrate OpenAI model

### ISSUE THREAD

**Issue by mlsm-trl** [eduardconstantin/storybook-gpt#22]
The API is returning error on generation:

```JSON
{
    "error": {
        "message": "The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}
```

Model `text-davinci-003` should be migrated to `gpt-3.5-turbo-instruct`

See notice about [models shutdown](https://platform.openai.com/docs/deprecations/2023-07-06-gpt-and-embeddings)

**Comment by eduardconstantin** [comment]
I updated the model to gpt-3.5-turbo-instruct
If everything is fine now please close the issue
