### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by tanish0912** [eduardconstantin/storybook-gpt#36]
The website is not mobile responsiveness, i aim to make it mobile responsive to give it a clean and professsional look on mobile devices.
Thanks, i am happy to contribute on this issue please assign this issue to me.

**Comment by tanish0912** [comment]
Please assign this issue to me.

**Comment by ayush1009208** [comment]
Hey tanish i have worked on such kinds of projects before...if you want you can assign this to me

**Comment by eduardconstantin** [comment]
Because you need to copy paste the components from your project the website doesn't really need a mobile version.
