### ISSUE TITLE
Responsiveness of the Page

### ISSUE THREAD

**Issue by Jils31** [eduardconstantin/storybook-gpt#37]
The page is not responsive , as it is not portable for the other devices.

[Screencast from 2024-10-10 02-48-45.webm](https://github.com/user-attachments/assets/812893b8-0356-4e51-8970-f2d11c985a1e)

I can solve this issue , Please assign this issue to me!

**Comment by eduardconstantin** [comment]
I guess we can have a tablet version, but don't bother for the mobile version

**Comment by eduardconstantin** [comment]
@Jils31 are you working on this issue?

**Comment by mahenoorsalat** [comment]
@eduardconstantin can you assign me this issue
I will look into this .. Looking forward to your response :)
