### ISSUE TITLE
[Feature] Improve the UI design

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/storybook-gpt#4]
The current design is a bit too dark.
I am open to any suggestions about improving the UI design, making it more pleasing.

**Comment by etnlbck** [comment]
Are you thinking of having something like a toggle between light and dark? Either via a button or detecting user system preferences?

**Comment by eduardconstantin** [comment]
I was thinking to lighten the dark UI a little bit. I think the shades are too dark. 
If you think having a dark and a light mode could improve the UI you can try to implement it.

**Comment by etnlbck** [comment]
I agree. It could use more contrast with a subtle gradient to give dimension. You can assign this issue to me.

**Comment by etnlbck** [comment]
How do you feel about this for lightening the dark UI?
<img width="600" alt="Screenshot 2023-10-01 at 1 08 38 PM" src="https://github.com/eduardconstantin/storybook-gpt/assets/386143/fcb52903-161a-4147-a79d-109e48155494">
I also added a responsive class so users can use it on mobile.
<img width="600" alt="Screenshot 2023-10-01 at 1 14 06 PM" src="https://github.com/eduardconstantin/storybook-gpt/assets/386143/360fffe6-4f18-4794-9368-b67f15dd21a0">

**Comment by eduardconstantin** [comment]
I think it's too much gradient.
I don't think anyone will use the mobile version but is a nice addition.
Also could you add a margin on the top and bottom? let's say 2-3rem maybe

**Comment by etnlbck** [comment]
Sounds good. And I agree. The user isn't going to copy/paste their component on mobile.

I'll make the adjustments this evening.


Also, I ran into an issue with theme context and RSC. I haven't worked with RSC before.

**Comment by eduardconstantin** [comment]
@etnlbck Sounds great!
RSC you mean react styled components? Because the project is using tailwind for styling.

**Comment by etnlbck** [comment]
React Server Components. 

Next was being cranky when I tried to use setState because it can only be used on the client. Then I tried adding the recommended "use client" annotation. But since the metadata is exported it gets treated a server.

**Comment by eduardconstantin** [comment]
I see, server components are the trouble, maybe tailwind can help

**Comment by eduardconstantin** [comment]
You can leave the theme toggle and focus on the UI for now.
Maybe you can create an issue for the toggle.

**Comment by etnlbck** [comment]
I'll do that. So That I'm not holding up this issue.

**Comment by etnlbck** [comment]
does this fall in line with what you're thinking. ![Screenshot 2023-10-07 at 10 43 20 AM](https://github.com/eduardconstantin/storybook-gpt/assets/386143/40e05b02-bf14-4fc4-9de1-54b0453750c3)

**Comment by eduardconstantin** [comment]
this looks nice
